Improve how google task is executed

diff --git a/run-checks b/run-checks
--- a/run-checks
+++ b/run-checks
@@ -25,18 +25,18 @@ git clone https://github.com/snapcore/snapd.git "$SNAPD_DIR"
 
 # Run spread-images task
 cd "$SPREAD_IMAGES_DIR"
-SPREAD_TMP_IMAGE_ID=
 if [ "$RUN_SNAPD" = "true" ]; then
-	SPREAD_TMP_IMAGE_ID="$TMP_IMAGE_ID"
-    echo "Running spread-images task and creating tmp image"
-fi
-
-if ! SPREAD_TMP_IMAGE_ID="$TMP_IMAGE_ID" spread "google:${SOURCE_SYSTEM}:tasks/google/${GOOGLE_ACTION}/${GOOGLE_TASK}"; then
-	echo "Spread images task failed, exiting..."
-	exit 1
-fi
-
-if [ "$RUN_SNAPD" != "true" ]; then
+	echo "Running spread-images task and creating tmp image"
+    if ! SPREAD_TMP_IMAGE_ID="$TMP_IMAGE_ID" spread "google:${SOURCE_SYSTEM}:tasks/google/${GOOGLE_ACTION}/${GOOGLE_TASK}"; then
+		echo "Spread images task failed, exiting..."
+		exit 1
+	fi
+else
+	echo "Running spread-images task and creating final image"
+	if ! spread "google:${SOURCE_SYSTEM}:tasks/google/${GOOGLE_ACTION}/${GOOGLE_TASK}"; then
+		echo "Spread images task failed, exiting..."
+		exit 1
+	fi
 	exit
 fi
 
